[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; board_build.f_flash = 80000000L
board_build.psram_size = 8MB
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
; board_build.filesystem = littlefs

upload_speed = 921600
monitor_speed = 115200

; Reserved Pins (Do Not Use):
;  - SPI Flash/PSRAM: GPIO26, GPIO27, GPIO28, GPIO29, GPIO30, GPIO31, GPIO32, GPIO33, GPIO34, GPIO35, GPIO36, GPIO37.
;  - Note: If your module uses Octal SPI (like the ESP32-S3-WROOM-1), GPIO35, GPIO36, and GPIO37 are always used for memory.
;  - Strapping Pins (Use with Caution):
;      GPIO0: Boot mode (connected to Boot button).
;      GPIO3: Strapping pin.
;      GPIO45: Strapping pin (VDD_SPI voltage selection).
;      GPIO46: Strapping pin.
;  - ADC2 Limitations: ADC2 (GPIO11-20) cannot be used while Wi-Fi is active. 
;
  ; I.e. do not use GPIO 0, 3, 26-37, 45 and 46. Also do not use ADC on GPIO 11-20.

build_flags =
    -DDISPLAY_REFRESH_MS=50  ; Refresh display every 20ms (50 FPS)
    ;
    ; TFT_eSPI configuration for GC9A01 round display
    -DDISABLE_ALL_LIBRARY_WARNINGS=1  ; for TFT_eSPI
    -DUSER_SETUP_LOADED=1
    -DGC9A01_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DSPI_FREQUENCY=40000000
    -DLOAD_GLCD=1   ; Original Adafruit 8 pixel font
    -DLOAD_FONT2=1 ; Small 16 pixel high font
    -DLOAD_FONT4=1 ; Medium 26 pixel high font
    ; -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    ;
    ; === ESP32 pins connections ===
    ;
    ; GC9A01 TFT display: connected to the VSPI bus with unused MISO pin
    -DTFT_ROTATION=0   ; 1 = horizontal, connector on the right, 0 = vertical, connector at the bottom
    -DTFT_MISO=-1
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=9
    -DTFT_RST=8
    -DPIN_TFT_BL=-1
    ;
    ; ----- Servo outputs -----
    -DPIN_SERVO_1=6
    -DPIN_SERVO_2=7
    -DPIN_SERVO_3=15
    -DPIN_SERVO_4=16
    -DPIN_SERVO_5=17
    -DPIN_SERVO_6=18
    ;
    ; === Other settings ===
    ;
    ; PSRAM
    -DBOARD_HAS_PSRAM=1
    ;
    ; Serial on the default USB:
    -D ARDUINO_USB_MODE=1
    ; -D ARDUINO_USB_CDC_ON_BOOT=1
    ;

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    tzapu/WiFiManager @ ^2.0.17

